# Name of website
title: DnA  # Or whatever you prefer

# Your name to show in the footer (optional, you can remove if not wanted)
author: Diyag.V.Anish

# URL of your website (very important)
url: "https://diyagv5.github.io"
baseurl: ""

# --- List of links in the navigation bar --- #
navbar-links:
  Photos: "photos/"  # We will create a page at /photos.md or /photos/index.md
  Videos: "videos/"  # We will create a page at /videos.md or /videos/index.md
# About Me: "aboutme/" # You can add an about page later if you wish

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# To use, first upload your image to /assets/img/your-avatar.png
# avatar: "/assets/img/your-avatar.png"
round-avatar: true # Set to false if you use an avatar and don't want it round

# --- Footer social media links (optional) --- #
# Uncomment and fill in any you want to use. Remove or keep commented out the rest.
social-network-links:
# email: "your.email@example.com"
# instagram: your_instagram_username
# youtube: YourYouTubeChannel
# github: Diyagv5 # If you want to link to your GitHub profile

# --- General options --- #
# How to display the link to your website in the footer (optional)
# url-pretty: "DnA-Photography.com" # Or whatever you want to display

# Add a search button to the navbar (can be useful if you add many items)
post_search: true

######################################
# --- Colours / background image --- #
# You can play with these later if you want to customize colors
######################################
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
site-css:
  - "/assets/css/custom.css"
#################################################################################
# --- You probably don't need to touch anything below here for now --- #
#################################################################################
timezone: "America/Toronto" # You can change this to your timezone if you know it, e.g. "Asia/Kolkata"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/ # Less relevant if not blogging
paginate: 5 # Less relevant if not blogging

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts" # Default settings for blog posts (if you ever add them)
    values:
      layout: "post"
      comments: false # Disable comments by default
      social-share: false # Disable social sharing buttons by default
  -
    scope:
      path: "" # Default layout for other pages
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
